(function(g){g.extend(_TMS,{presets:{zoomer:{reverseWay:!1,duration:"800",interval:"1",blocksX:"1",blocksY:"1",easing:"",way:"lines",anim:"zoomer",k:1.8,crds:{bottom:0,right:0}},fadeThree:{reverseWay:!1,duration:"800",interval:"1",blocksX:"1",blocksY:"1",easing:"",way:"lines",anim:"fadeThree"},simpleFade:{reverseWay:!1,duration:"800",interval:"1",blocksX:"1",blocksY:"1",easing:"",way:"lines",anim:"fade"},gSlider:{reverseWay:!1,duration:400,interval:40,blocksX:"1",blocksY:"1",easing:"",way:"lines",
anim:"gSlider"},vSlider:{reverseWay:!1,duration:400,interval:40,blocksX:"1",blocksY:"1",easing:"",way:"lines",anim:"vSlider"},slideFromLeft:{reverseWay:!1,duration:"800",interval:"1",blocksX:"1",blocksY:"1",easing:"easeOutBack",way:"lines",anim:"slideFromLeft"},slideFromTop:{reverseWay:!1,duration:"800",interval:"1",blocksX:"1",blocksY:"1",easing:"easeOutBack",way:"lines",anim:"slideFromTop"},diagonalFade:{reverseWay:!1,duration:400,interval:40,blocksX:12,blocksY:6,easing:"easeInQuad",way:"diagonal",
anim:"fade"},diagonalExpand:{reverseWay:!1,duration:400,interval:40,blocksX:10,blocksY:6,easing:"easeInQuad",way:"diagonal",anim:"expand"},fadeFromCenter:{reverseWay:!0,duration:"600",interval:"10",blocksX:"10",blocksY:"6",easing:"",way:"spiral",anim:"fade"},zabor:{reverseWay:!1,duration:400,interval:40,blocksX:"20",blocksY:"1",easing:"",way:"lines",anim:"slideRight"},vertivalLines:{reverseWay:!1,duration:600,interval:1,blocksX:12,blocksY:1,easing:"swing",way:"lines",anim:"vSlideOdd"},gorizontalLines:{reverseWay:!1,
duration:600,interval:1,blocksX:1,blocksY:12,easing:"swing",way:"lines",anim:"gSlideOdd"}},ways:{lines:function(){for(var b=[],d=0;d<this.maskC.length;d++)b.push(this.maskC.eq(d));return b},spiral:function(){var b=this,d=[],a=0,c=b.blocksY,f=b.blocksX,e,g=function(){for(e=a;e<f-1-a;e++)if(d.length<b.maskC.length)d.push(b.matrix[a][e]);else return!1;a:{for(e=a;e<c-1-a;e++)if(d.length<b.maskC.length)d.push(b.matrix[e][f-1-a]);else break a;b:{for(e=a;e<f-1-a;e++)if(d.length<b.maskC.length)d.push(b.matrix[c-
1-a][f-e-1]);else break b;c:{for(e=a;e<c-1-a;e++)if(d.length<b.maskC.length)d.push(b.matrix[c-e-1][a]);else break c;g(a++)}}}};g();return d},vSnake:function(){var b=[],d=this.blocksY,a=this.blocksX,c,f;for(f=0;f<a;f++)for(c=0;c<d;c++)0.5*f==~~(f/2)?b.push(this.matrix[c][f]):b.push(this.matrix[d-1-c][f]);return b},gSnake:function(){var b=[],d=this.blocksY,a=this.blocksX,c,f;for(f=0;f<d;f++)for(c=0;c<a;c++)0.5*f==~~(f/2)?b.push(this.matrix[f][c]):b.push(this.matrix[f][a-1-c]);return b},diagonal:function(){for(var b=
[],d=this.blocksY,a=this.blocksX,c=j=n=0,c=0;c<a;c++){b[c]=[];for(j=0;j<=c;j++)j<d&&b[c].push(this.matrix[j][c-j])}for(c=1;c<d;c++){j=0;for(b[n=b.length]=[];j<d-c;j++)b[n].push(this.matrix[c+j][a-1-j])}return b},chess:function(){for(var b=0,d=[[],[]],a=0;b<this.maskC.length;b++)d[a=a?0:1].push(this.maskC.eq(b));return d},randomly:function(){var b=[];for(i=0;i<this.maskC.length;i++)b.push(this.maskC.eq(i));for(i=0;i<this.maskC.length;i++)b.push(b.splice(parseInt(Math.random()*this.maskC.length-1),
1)[0]);return b}},anims:{fadeThree:function(b,d){var a=this;g(b).each(function(){var c=g(this).show().css({left:-a.width/4,top:0,zIndex:2}),b=c.clone().appendTo(c.parent()).css({left:a.width/4,top:a.height/4,zIndex:1}),e=c.clone().appendTo(c.parent()).css({left:0,top:-a.height/4,zIndex:1});b.stop().animate({left:0,top:0},{duration:a.duration,easing:a.easing});e.stop().animate({left:0,top:0},{duration:a.duration,easing:a.easing});c.stop().animate({left:0,top:0},{duration:a.duration,easing:a.easing,
step:function(d){d=1+d/a.width;b.css({opacity:d*d});e.css({opacity:d*d});c.css({opacity:d*d*d})},complete:function(){d&&a.afterShow();b.remove();e.remove()}})})},zoomer:function(b,d){var a=this;g(b).each(function(){g(this);var c=g(new Image),b=0<a.direction?a.width*a.k:a.width,e=0<a.direction?a.width:a.width*a.k;console.log(b+" "+e);c.css({position:"absolute",zIndex:0,opacity:0}).css(a.crds).appendTo(a.pic).load(function(){a.pic.find("img").not(c).remove();c.css({width:b,height:"auto"}).stop().animate({opacity:1},
{duration:200}).animate({width:e},{duration:a.duration,easing:a.easing});setTimeout(function(){d&&a.afterShow()},400)}).attr({src:a.next})})},fade:function(b,d){var a=this;g(b).each(function(){g(this).css({opacity:0}).show().stop().animate({opacity:1},{duration:+a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}})})},expand:function(b,d){var a=this;g(b).each(function(){g(this).hide().show(+a.duration,function(){d&&a.afterShow()})})},slideDown:function(b,d){var a=this;g(b).each(function(){var c=
g(this).show(),b=c.height();c.css({height:0}).stop().animate({height:b},{duration:a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}})})},slideLeft:function(b,d){var a=this;g(b).each(function(){var c=g(this).show(),b=c.width();c.css({width:0}).stop().animate({width:b},{duration:a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}})})},slideUp:function(b,d){var a=this;g(b).each(function(){var c=g(this).show(),b=c.height(),e=c.attr("offsetLeft"),h=c.attr("offsetTop");c.css({height:0,
top:h+b}).stop().animate({height:b},{duration:a.duration,easing:a.easing,step:function(a){a=h+b-a;c.css({top:a,backgroundPosition:"-"+e+"px -"+a+"px"})},complete:function(){d&&a.afterShow()}})})},slideRight:function(b,d){var a=this;g(b).each(function(){var c=g(this).show(),b=c.width(),e=c.attr("offsetLeft"),h=c.attr("offsetTop");c.css({width:0,left:e+b}).stop().animate({width:b},{duration:a.duration,easing:a.easing,step:function(a){a=e+b-a;c.css({left:a,backgroundPosition:"-"+a+"px -"+h+"px"})},complete:function(){d&&
a.afterShow()}})})},slideFromTop:function(b,d){var a=this;g(b).each(function(){var c=g(this),b=c.show().css("top"),e=c.height();c.css({top:-e}).stop().animate({top:b},{duration:+a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}})})},slideFromDown:function(b,d){var a=this;g(b).each(function(){var c=g(this),b=c.show().css("top"),e=c.height();c.css({top:e}).stop().animate({top:b},{duration:+a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}})})},slideFromLeft:function(b,
d){var a=this;g(b).each(function(){var c=g(this),b=c.show().css("left"),e=c.width();c.css({left:-e}).stop().animate({left:b},{duration:+a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}})})},slideFromRight:function(b,d){var a=this;g(b).each(function(){var b=g(this),f=b.show().css("left"),e=b.width();b.css({left:e}).stop().animate({left:f},{duration:+a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}})})},gSlider:function(b,d){var a=this,c=a.maskC.clone(),f=c.width();c.appendTo(a.maskC.parent()).css({background:a.pic.css("backgroundImage")}).show();
b.show().css({left:0<a.direction?-f:f}).stop().animate({left:0},{duration:+a.duration,easing:a.easing,step:function(b){0<a.direction?c.css("left",b+f):c.css("left",b-f)},complete:function(){c.remove();d&&a.afterShow()}})},vSlider:function(b,d){var a=this,c=a.maskC.clone(),f=c.height();c.appendTo(a.maskC.parent()).css({background:a.pic.css("backgroundImage")}).show();b.show().css({top:0<a.direction?-f:f}).stop().animate({top:0},{duration:+a.duration,easing:a.easing,step:function(b){0<a.direction?c.css("top",
b+f):c.css("top",b-f)},complete:function(){c.remove();d&&a.afterShow()}})},vSlideOdd:function(b,d){var a=this;g(b).each(function(){var b=g(this),f=b.show().css("top"),e=b.height();b.css({top:a.odd?-e:e}).stop().animate({top:f},{duration:+a.duration,easing:a.easing,complete:function(){d&&a.afterShow()}});a.odd=a.odd?!1:!0})},gSlideOdd:function(b,d){var a=this;g(b).each(function(){var b=g(this),f=b.show().css("left"),e=b.width();b.css({left:a.odd?-e:e}).stop().animate({left:f},{duration:+a.duration,
easing:a.easing,complete:function(){d&&a.afterShow()}});a.odd=a.odd?!1:!0})}}})})(jQuery);